### ISSUE TITLE
Come up with alerting solution for servers

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/infrastructure#107]

**Comment by jamezpolley** [comment]
After investigating NewRelic Infra pricing, we've found it to be much more reasonably priced than we'd expected. We've now had it enabled on our account and rolled it out across the fleet. We already have some alerts from our earlier trial, so we're now getting alerting to Slack, and mobile push alerts are an option too.

We probably want to tweak some of the thresholds - eg, Morph is consistently sitting at ~88% memory used which is considered critical; for that machine it should probably be something like 2Gb free instead of the usual threshold.
